//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterTwitter.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InterTwitter.Resources.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Blacklist.
        /// </summary>
        internal static string AddToBlacklist {
            get {
                return ResourceManager.GetString("AddToBlacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Mute.
        /// </summary>
        internal static string AddToMute {
            get {
                return ResourceManager.GetString("AddToMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database failure.
        /// </summary>
        internal static string AlertDatabase {
            get {
                return ResourceManager.GetString("AlertDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data is incorrectly filled.
        /// </summary>
        internal static string AlertDataIncorrect {
            get {
                return ResourceManager.GetString("AlertDataIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is empty.
        /// </summary>
        internal static string AlertEmailEmpty {
            get {
                return ResourceManager.GetString("AlertEmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email does not match the format.
        /// </summary>
        internal static string AlertEmailInvalid {
            get {
                return ResourceManager.GetString("AlertEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Email there is no symbol @.
        /// </summary>
        internal static string AlertEmailNoA {
            get {
                return ResourceManager.GetString("AlertEmailNoA", resourceCulture);
            }
        }
        
        internal static string AlertErrorTrimmingVideo {
            get {
                return ResourceManager.GetString("AlertErrorTrimmingVideo", resourceCulture);
            }
        }
        
        
        internal static string AlertFileNotExist {
            get {
                return ResourceManager.GetString("AlertFileNotExist", resourceCulture);
            }
        }

        internal static string AlertInvalidLogin {
            get {
                return ResourceManager.GetString("AlertInvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password!.
        /// </summary>
        internal static string AlertInvalidPassword {
            get {
                return ResourceManager.GetString("AlertInvalidPassword", resourceCulture);
            }
        }
        
        internal static string AlertLimitSizeGif {
            get {
                return ResourceManager.GetString("AlertLimitSizeGif", resourceCulture);
            }
        }

        internal static string AlertLimitSizePhoto {
            get {
                return ResourceManager.GetString("AlertLimitSizePhoto", resourceCulture);
            }
        }
        
        internal static string AlertLimitSizeVideo {
            get {
                return ResourceManager.GetString("AlertLimitSizeVideo", resourceCulture);
            }
        }
        
        internal static string AlertLoginNotExist {
            get {
                return ResourceManager.GetString("AlertLoginNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This login is already taken.
        /// </summary>
        internal static string AlertLoginTaken {
            get {
                return ResourceManager.GetString("AlertLoginTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is empty.
        /// </summary>
        internal static string AlertNameEmpty {
            get {
                return ResourceManager.GetString("AlertNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name cannot be shorter 2 character.
        /// </summary>
        internal static string AlertNameLength {
            get {
                return ResourceManager.GetString("AlertNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name includes only letters.
        /// </summary>
        internal static string AlertNameLetter {
            get {
                return ResourceManager.GetString("AlertNameLetter", resourceCulture);
            }
        }
        
        internal static string AlertNeedAccessPhotosGallery {
            get {
                return ResourceManager.GetString("AlertNeedAccessPhotosGallery", resourceCulture);
            }
        }

        internal static string AlertOnlyGif {
            get {
                return ResourceManager.GetString("AlertOnlyGif", resourceCulture);
            }
        }
        
        internal static string AlertOnlyPicture {
            get {
                return ResourceManager.GetString("AlertOnlyPicture", resourceCulture);
            }
        }
        
        internal static string AlertPasswordEmpty {
            get {
                return ResourceManager.GetString("AlertPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password less than 6 characters.
        /// </summary>
        internal static string AlertPasswordLength {
            get {
                return ResourceManager.GetString("AlertPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain a big letter and digit.
        /// </summary>
        internal static string AlertPasswordLetterDigit {
            get {
                return ResourceManager.GetString("AlertPasswordLetterDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirm password do not coincide.
        /// </summary>
        internal static string AlertPasswordNotEqual {
            get {
                return ResourceManager.GetString("AlertPasswordNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is already blocked.
        /// </summary>
        internal static string AlreadyBlocked {
            get {
                return ResourceManager.GetString("AlreadyBlocked", resourceCulture);
            }
        }
        
        internal static string Blacklist {
            get {
                return ResourceManager.GetString("Blacklist", resourceCulture);
            }
        }

        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Bookmarks {
            get {
                return ResourceManager.GetString("Bookmarks", resourceCulture);
            }
        }

        internal static string ConfirmComeBack {
            get {
                return ResourceManager.GetString("ConfirmComeBack", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Change profile.
        /// </summary>
        internal static string ChangeProfile {
            get {
                return ResourceManager.GetString("ChangeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your account.
        /// </summary>
        internal static string CreateYourAccount {
            get {
                return ResourceManager.GetString("CreateYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all bookmarks.
        /// </summary>
        internal static string DeleteAllbookmarks {
            get {
                return ResourceManager.GetString("DeleteAllbookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not match.
        /// </summary>
        internal static string DoNotMatch {
            get {
                return ResourceManager.GetString("DoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid or empty.
        /// </summary>
        internal static string EmailIsNotValid {
            get {
                return ResourceManager.GetString("EmailIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tweets found.
        /// </summary>
        internal static string FailureUsersNotFound {
            get {
                return ResourceManager.GetString("FailureUsersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from the Blacklist.
        /// </summary>
        internal static string FromTheBlacklist {
            get {
                return ResourceManager.GetString("FromTheBlacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from the mute.
        /// </summary>
        internal static string FromTheMute {
            get {
                return ResourceManager.GetString("FromTheMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get your account.
        /// </summary>
        internal static string GetYourAccount {
            get {
                return ResourceManager.GetString("GetYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For a more accurate search, enter 2 or more characters.
        /// </summary>
        internal static string InaccurateRequest {
            get {
                return ResourceManager.GetString("InaccurateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid link to user profile.
        /// </summary>
        internal static string InvalidLinkToUserProfile {
            get {
                return ResourceManager.GetString("InvalidLinkToUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likes.
        /// </summary>
        internal static string Likes {
            get {
                return ResourceManager.GetString("Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        internal static string Mute {
            get {
                return ResourceManager.GetString("Mute", resourceCulture);
            }
        }
        
        internal static string Muted {
            get {
                return ResourceManager.GetString("Muted", resourceCulture);
            }
        }

        internal static string MutedProfiles {
            get {
                return ResourceManager.GetString("MutedProfiles", resourceCulture);
            }
        }

        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is not valid or empty.
        /// </summary>
        internal static string NameIsNotValid {
            get {
                return ResourceManager.GetString("NameIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is not valid or empty.
        /// </summary>
        internal static string NewPasswordIsNotValid {
            get {
                return ResourceManager.GetString("NewPasswordIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Next     .
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        internal static string NoResultsFor {
            get {
                return ResourceManager.GetString("NoResultsFor", resourceCulture);
            }
        }
        
        internal static string NotFoundBookmark {
            get {
                return ResourceManager.GetString("NotFoundBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not found any like.
        /// </summary>
        internal static string NotFoundLike {
            get {
                return ResourceManager.GetString("NotFoundLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found notification.
        /// </summary>
        internal static string NotFoundNotification {
            get {
                return ResourceManager.GetString("NotFoundNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tweets found.
        /// </summary>
        internal static string NoTweets {
            get {
                return ResourceManager.GetString("NoTweets", resourceCulture);
            }
        }
        
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is empty.
        /// </summary>
        internal static string OldPassEmpty {
            get {
                return ResourceManager.GetString("OldPassEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is wrong.
        /// </summary>
        internal static string OldPassWrong {
            get {
                return ResourceManager.GetString("OldPassWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is incorrect.
        /// </summary>
        internal static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, type your name.
        /// </summary>
        internal static string PleaseName {
            get {
                return ResourceManager.GetString("PleaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular theme.
        /// </summary>
        internal static string PopularTheme {
            get {
                return ResourceManager.GetString("PopularTheme", resourceCulture);
            }
        }
        
        internal static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }

        internal static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }

        
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile in Blacklist.
        /// </summary>
        internal static string ProfileInBlacklist {
            get {
                return ResourceManager.GetString("ProfileInBlacklist", resourceCulture);
            }
        }

        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }

        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        internal static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }

        internal static string YouNeedPassword {
            get {
                return ResourceManager.GetString("YouNeedPassword", resourceCulture);
            }
        }
        
        internal static string SomeIssues {
            get {
                return ResourceManager.GetString("SomeIssues", resourceCulture);
            }
        }
        
        internal static string UserBlocked {
            get {
                return ResourceManager.GetString("UserBlocked", resourceCulture);
            }
        }
        
        internal static string UserMuted {
            get {
                return ResourceManager.GetString("UserMuted", resourceCulture);
            }
        }

        internal static string ToBlacklist {
            get {
                return ResourceManager.GetString("ToBlacklist", resourceCulture);
            }
        }

        internal static string ToMute {
            get {
                return ResourceManager.GetString("ToMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User can see information about you.
        /// </summary>
        internal static string UserCanSeeInfo {
            get {
                return ResourceManager.GetString("UserCanSeeInfo", resourceCulture);
            }
        }

        internal static string UserNotSeeYouPost {
            get {
                return ResourceManager.GetString("UserNotSeeYouPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Email.
        /// </summary>
        internal static string WrongEmail {
            get {
                return ResourceManager.GetString("WrongEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong result.
        /// </summary>
        internal static string WrongResult {
            get {
                return ResourceManager.GetString("WrongResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no bookmarks yet.
        /// </summary>
        internal static string YouHaveNoBookmarks {
            get {
                return ResourceManager.GetString("YouHaveNoBookmarks", resourceCulture);
            }
        }
    }
}
