//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterTwitter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InterTwitter.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to mute?.
        /// </summary>
        public static string _to_mute_ {
            get {
                return ResourceManager.GetString("_to mute?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to Blacklist?.
        /// </summary>
        public static string _toBlacklist_ {
            get {
                return ResourceManager.GetString("_toBlacklist?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add_ {
            get {
                return ResourceManager.GetString("Add_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Blacklist.
        /// </summary>
        public static string Add_to_Blacklist {
            get {
                return ResourceManager.GetString("Add to Blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Mute.
        /// </summary>
        public static string Add_to_Mute {
            get {
                return ResourceManager.GetString("Add to Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database failure.
        /// </summary>
        public static string AlertDatabase {
            get {
                return ResourceManager.GetString("AlertDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data is incorrectly filled.
        /// </summary>
        public static string AlertDataIncorrect {
            get {
                return ResourceManager.GetString("AlertDataIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is empty.
        /// </summary>
        public static string AlertEmailEmpty {
            get {
                return ResourceManager.GetString("AlertEmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email does not match the format.
        /// </summary>
        public static string AlertEmailInvalid {
            get {
                return ResourceManager.GetString("AlertEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Email there is no symbol @.
        /// </summary>
        public static string AlertEmailNoA {
            get {
                return ResourceManager.GetString("AlertEmailNoA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login!.
        /// </summary>
        public static string AlertInvalidLogin {
            get {
                return ResourceManager.GetString("AlertInvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password!.
        /// </summary>
        public static string AlertInvalidPassword {
            get {
                return ResourceManager.GetString("AlertInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This login does not exist.
        /// </summary>
        public static string AlertLoginNotExist {
            get {
                return ResourceManager.GetString("AlertLoginNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This login is already taken.
        /// </summary>
        public static string AlertLoginTaken {
            get {
                return ResourceManager.GetString("AlertLoginTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is empty.
        /// </summary>
        public static string AlertNameEmpty {
            get {
                return ResourceManager.GetString("AlertNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name cannot be shorter 2 character.
        /// </summary>
        public static string AlertNameLength {
            get {
                return ResourceManager.GetString("AlertNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name includes only letters.
        /// </summary>
        public static string AlertNameLetter {
            get {
                return ResourceManager.GetString("AlertNameLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is empty.
        /// </summary>
        public static string AlertPasswordEmpty {
            get {
                return ResourceManager.GetString("AlertPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password less than 6 characters.
        /// </summary>
        public static string AlertPasswordLength {
            get {
                return ResourceManager.GetString("AlertPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain a big letter and digit.
        /// </summary>
        public static string AlertPasswordLetterDigit {
            get {
                return ResourceManager.GetString("AlertPasswordLetterDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirm password do not coincide.
        /// </summary>
        public static string AlertPasswordNotEqual {
            get {
                return ResourceManager.GetString("AlertPasswordNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is already blocked.
        /// </summary>
        public static string AlreadyBlocked {
            get {
                return ResourceManager.GetString("AlreadyBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your account.
        /// </summary>
        public static string CreateYourAccount {
            get {
                return ResourceManager.GetString("CreateYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not match.
        /// </summary>
        public static string DoNotMatch {
            get {
                return ResourceManager.GetString("DoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid or empty.
        /// </summary>
        public static string Email_is_not_valid_or_empty {
            get {
                return ResourceManager.GetString("Email is not valid or empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tweets found.
        /// </summary>
        public static string FailureUsersNotFound {
            get {
                return ResourceManager.GetString("FailureUsersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from the Blacklist.
        /// </summary>
        public static string from_the_Blacklist {
            get {
                return ResourceManager.GetString("from the Blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from the mute.
        /// </summary>
        public static string from_the_mute {
            get {
                return ResourceManager.GetString("from the mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get your account.
        /// </summary>
        public static string GetYourAccount {
            get {
                return ResourceManager.GetString("GetYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likes.
        /// </summary>
        public static string Likes {
            get {
                return ResourceManager.GetString("Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is not valid or empty.
        /// </summary>
        public static string Name_is_not_valid_or_empty {
            get {
                return ResourceManager.GetString("Name is not valid or empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is not valid or empty.
        /// </summary>
        public static string New_password_is_not_valid_or_empty {
            get {
                return ResourceManager.GetString("New password is not valid or empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is empty.
        /// </summary>
        public static string Old_password_is_empty {
            get {
                return ResourceManager.GetString("Old password is empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is wrong.
        /// </summary>
        public static string Old_password_is_wrong {
            get {
                return ResourceManager.GetString("Old password is wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is incorrect.
        /// </summary>
        public static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, type your name.
        /// </summary>
        public static string PleaseName {
            get {
                return ResourceManager.GetString("PleaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string Save_changes {
            get {
                return ResourceManager.GetString("Save changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is already blocked.
        /// </summary>
        public static string This_user_is_already_blocked {
            get {
                return ResourceManager.GetString("This user is already blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is already muted.
        /// </summary>
        public static string This_user_is_already_muted {
            get {
                return ResourceManager.GetString("This user is already muted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user will not see your posts..
        /// </summary>
        public static string This_user_will_not_see_your_posts {
            get {
                return ResourceManager.GetString("This user will not see your posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User can see information about you.
        /// </summary>
        public static string User_can_see_information_about_you {
            get {
                return ResourceManager.GetString("User can see information about you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Email.
        /// </summary>
        public static string WrongEmail {
            get {
                return ResourceManager.GetString("WrongEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll need a password.
        /// </summary>
        public static string YouNeedPassword {
            get {
                return ResourceManager.GetString("YouNeedPassword", resourceCulture);
            }
        }
    }
}
